from utils import dot_product, avr_lists
from Player import Player
from Team import Team
import heapq


#These vectors are generated by claude so we need to make sure that they are fine!!!
#Medicine, Biology, Chemistry, Physics, Engineering, Coding, Math, Hands-on Degree
anatomy              = (0.9, 0.6, 0.2, 0.0, 0.0, 0.0, 0.1, 0.2)
astronomy            = (0.0, 0.0, 0.1, 0.9, 0.0, 0.1, 0.5, 0.2)
boomilever           = (0.0, 0.0, 0.0, 0.7, 1.0, 0.0, 0.4, 1.0)
botany               = (0.1, 0.9, 0.2, 0.0, 0.0, 0.0, 0.1, 0.3)
chemistry_lab        = (0.0, 0.0, 1.0, 0.3, 0.0, 0.0, 0.5, 0.8)
circuit_lab          = (0.0, 0.0, 0.1, 0.9, 0.6, 0.0, 0.4, 0.9)
codebusters          = (0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.8, 0.1)
designer_genes       = (0.3, 0.9, 0.3, 0.0, 0.0, 0.0, 0.3, 0.3)
disease_detectives   = (0.7, 0.6, 0.1, 0.0, 0.0, 0.0, 0.5, 0.2)
dynamic_planet       = (0.0, 0.2, 0.3, 0.4, 0.0, 0.0, 0.3, 0.2)
electric_vehicle     = (0.0, 0.0, 0.1, 0.8, 1.0, 0.1, 0.4, 1.0)
engineering_cad      = (0.0, 0.0, 0.0, 0.3, 0.9, 0.2, 0.5, 0.6)
experimental_design  = (0.1, 0.3, 0.3, 0.3, 0.1, 0.0, 0.6, 0.7)
forensics            = (0.2, 0.3, 0.7, 0.2, 0.0, 0.0, 0.3, 0.7)
hovercraft           = (0.0, 0.0, 0.0, 0.8, 1.0, 0.0, 0.3, 1.0)
mission_possible     = (0.0, 0.0, 0.1, 0.7, 1.0, 0.0, 0.2, 1.0)
ping_pong_parachute  = (0.0, 0.0, 0.1, 0.8, 0.8, 0.0, 0.3, 1.0)
protein_modeling     = (0.3, 0.8, 0.5, 0.1, 0.2, 0.1, 0.2, 0.7)
remote_sensing       = (0.0, 0.2, 0.1, 0.4, 0.1, 0.4, 0.5, 0.3)
rocks_and_minerals   = (0.0, 0.0, 0.5, 0.2, 0.0, 0.0, 0.1, 0.5)
thermodynamics       = (0.0, 0.0, 0.3, 1.0, 0.6, 0.0, 0.5, 0.8)
water_quality        = (0.0, 0.6, 0.5, 0.1, 0.0, 0.0, 0.3, 0.3)
wright_stuff         = (0.0, 0.0, 0.0, 0.9, 0.8, 0.0, 0.3, 1.0)

# Optional: collect into one dict for easy iteration/analysis
events = {
    "Anatomy and Physiology": anatomy,
    "Botany": botany,
    "Designer Genes": designer_genes,
    "Disease Detectives": disease_detectives,
    "Water Quality": water_quality,
    "Astronomy": astronomy,
    "Dynamic Planet": dynamic_planet,
    "Remote Sensing": remote_sensing,
    "Rocks and Minerals": rocks_and_minerals,
    "Chemistry Lab": chemistry_lab,
    "Circuit Lab": circuit_lab,
    "Forensics": forensics,
    "Hovercraft": hovercraft,
    "Protein Modeling": protein_modeling,
    "Thermodynamics": thermodynamics,
    "Boomilever": boomilever,
    "Electric Vehicle": electric_vehicle,
    "Mission Possible": mission_possible,
    "Wright Stuff": wright_stuff,
    "Codebusters": codebusters,
    "Engineering CAD": engineering_cad,
    "Experimental Design": experimental_design,
    "Ping-Pong Parachute": ping_pong_parachute,
}

events_by_popularity = [
    'Anatomy and Physiology',
    'Chemistry Lab',
    'Protein Modeling',
    'Astronomy',
    'Ping-Pong Parachute',
    'Designer Genes',
    'Experimental Design',
    'Thermodynamics',
    'Forensics',
    'Disease Detectives',
    'Codebusters',
    'Circuit Lab',
    'Electric Vehicle',
    'Botany',
    'Hovercraft',
    'Dynamic Planet',
    'Wright Stuff',
    'Water Quality',
    'Remote Sensing',
    'Boomilever',
    'Rocks and Minerals',
    'Engineering CAD',
    'Mission Possible',
]

events_by_uniqueness = events_by_popularity[::-1]

middle_option_events = [item for pair in zip(events_by_popularity, events_by_uniqueness) for item in pair]

middle_option_events = middle_option_events[:len(middle_option_events)//2]

middle_option_flip = middle_option_events[::-1]

self_made = events_by_popularity[13::-1] + events_by_popularity[14::]
#print(self_made)
#print(middle_option_events)
people = {
    "neda_jantzen"           : ['Designer Genes', 'Rocks and Minerals', 'Forensics', 'Experimental Design'],
    "evelyn_leng"            : ['Designer Genes', 'Disease Detectives', 'Experimental Design'],
    "everett_mcglothlin"     : ['Astronomy', 'Codebusters', 'Engineering CAD'],
    #"samson_ou"              : ['Protein Modeling', 'Thermodynamics', 'Codebusters'],
    "yunes_adjerid"          : ['Anatomy and Physiology', 'Disease Detectives', 'Water Quality', 'Circuit Lab', 'Protein Modeling'],
    "milo_tao_lin"           : ['Circuit Lab', 'Protein Modeling', 'Thermodynamics'],
    "rey_han"                : ['Botany', 'Circuit Lab', 'Hovercraft'],
    "pam_kampanya"           : ['Anatomy and Physiology', 'Circuit Lab', 'Hovercraft'],
    "clara_cook"             : ['Anatomy and Physiology', 'Disease Detectives', 'Experimental Design'],
    "moses_park"             : ['Astronomy', 'Circuit Lab', 'Thermodynamics'],
    "siena_marr"             : ['Astronomy', 'Chemistry Lab', 'Experimental Design'],
    "hadley_teaster"         : ['Anatomy and Physiology', 'Designer Genes', 'Protein Modeling'],
    "jeannette_wang"         : ['Anatomy and Physiology', 'Designer Genes', 'Protein Modeling'],
    "ethan_zhu"              : ['Circuit Lab', 'Hovercraft', 'Electric Vehicle'],
    "david_hicks"            : ['Botany', 'Astronomy', 'Dynamic Planet'],
    "kora_pence"             : ['Botany', 'Designer Genes', 'Disease Detectives'],
    "meera_nair"             : ['Anatomy and Physiology', 'Forensics'],
    "ozan_tural"             : ['Anatomy and Physiology', 'Water Quality', 'Dynamic Planet', 'Protein Modeling', 'Thermodynamics'],
    "sophia_warren"          : ['Designer Genes', 'Chemistry Lab', 'Protein Modeling'],
    "jenny_li"               : ['Designer Genes', 'Forensics', 'Codebusters'],
    "giang_nguyen"           : ['Botany', 'Remote Sensing', 'Hovercraft', 'Boomilever', 'Wright Stuff', 'Codebusters'],
    #"sadie_zhang"            : ['Remote Sensing', 'Forensics', 'Ping-Pong Parachute'],
    "nathan_chen"            : ['Astronomy', 'Chemistry Lab', 'Circuit Lab', 'Thermodynamics', 'Codebusters', 'Experimental Design'],
    "andrew_hou"             : ['Anatomy and Physiology', 'Chemistry Lab', 'Protein Modeling'],
    "braulio_escalante"      : ['Botany', 'Water Quality', 'Rocks and Minerals'],
    "emma_hungate"           : ['Boomilever', 'Electric Vehicle', 'Mission Possible', 'Wright Stuff', 'Engineering CAD', 'Experimental Design', 'Ping-Pong Parachute'],
    "garrett_butler"         : ['Astronomy', 'Hovercraft', 'Electric Vehicle'],
    "owen_fotinos"           : ['Chemistry Lab', 'Protein Modeling', 'Thermodynamics', 'Boomilever'],
    #"grace_li"               : ['Anatomy and Physiology', 'Designer Genes', 'Water Quality'],
    "elisabeth_emmett"       : ['Anatomy and Physiology', 'Designer Genes', 'Disease Detectives'],
    "mirabella_garza"        : ['Anatomy and Physiology', 'Remote Sensing', 'Chemistry Lab'],
    #"mack_strahm"            : ['Chemistry Lab', 'Protein Modeling', 'Electric Vehicle'],
    "evan_weng"              : ['Water Quality', 'Dynamic Planet', 'Remote Sensing', 'Thermodynamics', 'Wright Stuff', 'Ping-Pong Parachute'],
    "sailor_long"            : ['Astronomy', 'Chemistry Lab', 'Forensics'],
    "sofia_mariani"          : ['Electric Vehicle', 'Mission Possible'],
    "atiksh_ajit"            : ['Anatomy and Physiology', 'Astronomy', 'Hovercraft', 'Electric Vehicle', 'Codebusters', 'Ping-Pong Parachute'],
    "henry_vikesland"        : ['Chemistry Lab', 'Electric Vehicle', 'Ping-Pong Parachute'],
    "adi_ali"                : ['Anatomy and Physiology', 'Chemistry Lab', 'Protein Modeling'],
    "zoe_zhang"              : ['Dynamic Planet', 'Wright Stuff', 'Ping-Pong Parachute'],
    #"nyala_smith"            : ['Anatomy and Physiology', 'Chemistry Lab', 'Wright Stuff'], I don't think that she wants to do SciOly anymore
    "margaret_martin"        : ['Chemistry Lab', 'Wright Stuff', 'Codebusters'],
    "dennis_zhao"            : ['Anatomy and Physiology', 'Dynamic Planet', 'Protein Modeling'],
    "rose_delong"            : ['Anatomy and Physiology', 'Botany', 'Astronomy', 'Rocks and Minerals', 'Chemistry Lab', 'Protein Modeling'],
    "maeve_holland"          : ['Anatomy and Physiology', 'Protein Modeling', 'Codebusters'],
    "stephen_duncan"         : ['Circuit Lab', 'Electric Vehicle', 'Ping-Pong Parachute'],
    "simon_jaworski"         : ['Astronomy', 'Chemistry Lab', 'Ping-Pong Parachute'],
    "hari_kumar"             : ['Astronomy', 'Chemistry Lab', 'Ping-Pong Parachute'],
    "isabella_baisden"       : ['Anatomy and Physiology', 'Disease Detectives', 'Forensics', 'Thermodynamics', 'Experimental Design'],
    "mira_davison"           : ['Anatomy and Physiology', 'Disease Detectives', 'Forensics', 'Thermodynamics', 'Experimental Design'],
    "natalia_migan_gandonou" : ['Anatomy and Physiology', 'Chemistry Lab', 'Forensics'],
    #"sophie_zhang"           : ['Botany', 'Disease Detectives', 'Astronomy', 'Dynamic Planet', 'Chemistry Lab', 'Protein Modeling', 'Boomilever', 'Ping-Pong Parachute'],
    "faiyaz_kabir"           : ['Anatomy and Physiology', 'Protein Modeling', 'Experimental Design'],
    "joshua_byun"            : ['Anatomy and Physiology', 'Astronomy', 'Chemistry Lab'],
    #"mateja_grove"           : ['Circuit Lab','Hovercraft','Electric Vehicle'],
    #"matthew_cao"            : ['Electric Vehicle','Hovercraft','Boomilever'],
    #"peyton_laird"           : ['Anatomy and Physiology','Designer Genes','Water Quality'],
}
officers = {
    "samson_ou"              : (['Protein Modeling', 'Thermodynamics', 'Codebusters'], 11),
    "grace_li"               : (['Anatomy and Physiology', 'Designer Genes', 'Water Quality'], 11),
    "mack_strahm"            : (['Chemistry Lab', 'Protein Modeling', 'Electric Vehicle'], 12),
    "sophie_zhang"           : (['Botany', 'Chemistry Lab', 'Boomilever'], 11),
    "mateja_grove"           : (['Circuit Lab','Hovercraft','Electric Vehicle'], 12),
    "matthew_cao"            : (['Electric Vehicle','Hovercraft','Boomilever'], 10),
    "peyton_laird"           : (['Anatomy and Physiology','Designer Genes','Water Quality'], 12),
}

grades = {
    "neda_jantzen": 11,
    "evelyn_leng": 10,
    "everett_mcglothlin": 10,
    #"samson_ou": 11,
    "yunes_adjerid": 10,
    "milo_tao_lin": 12,
    "rey_han": 11,
    "pam_kampanya": 10,
    "clara_cook": 10,
    "moses_park": 10,
    "siena_marr": 10,
    "hadley_teaster": 12,
    "jeannette_wang": 12,
    "ethan_zhu": 11,
    "david_hicks": 10,
    "kora_pence": 11,
    "meera_nair": 9,
    "ozan_tural": 12,
    "sophia_warren": 11,
    "jenny_li": 9,
    "giang_nguyen": 9,
    #"sadie_zhang": 11,
    "nathan_chen": 12,
    "andrew_hou": 12,
    "braulio_escalante": 12,
    "emma_hungate": 11,
    "garrett_butler": 11,
    "owen_fotinos": 12,
    #"grace_li": 11,
    "elisabeth_emmett": 12,
    "mirabella_garza": 12,
    #"mack_strahm": 12,
    "evan_weng": 9,
    "sailor_long": 12,
    "sofia_mariani": 11,
    "atiksh_ajit": 9,
    "henry_vikesland": 11,
    "adi_ali": 11,
    "zoe_zhang": 11,
    #"nyala_smith": 9,
    "margaret_martin": 9,
    "dennis_zhao": 11,
    "rose_delong": 9,
    "maeve_holland": 9,
    "stephen_duncan": 11,
    "simon_jaworski": 9,
    "hari_kumar": 9,
    "isabella_baisden": 11,
    "mira_davison": 11,
    "natalia_migan_gandonou": 9,
    #"sophie_zhang": 11,
    "faiyaz_kabir": 12,
    "joshua_byun": 12,
    #"mateja_grove": 12,
    #"matthew_cao": 10,
    #"peyton_laird": 12,
}

merged_dict = {key: (people[key], grades[key]) for key in people}
player_list = []
for person, values in merged_dict.items():
    variable_picks = []
    for event in values[0]:
        variable_picks.append(events.get(event))
    #print(variable_picks)
    player_list.append(Player(name = person, picks = variable_picks, grade = values[1]))


team1 = Team()
team2 = Team()
team3 = Team()
team4 = Team()
for officer, choices in officers.items():
    o = Player(name = officer, picks = [events.get(val) for val in officers.get(officer)[0]], grade = officers.get(officer)[1])
    for c in choices[0]:
        #print(c)
        team3.add_and_decrease(o, c)
#print(team3)

# for i in events_by_uniqueness:
#     event_pq = []
#     for p in (set(player_list)-team1.players-team2.players-team3.players):
#         if i in p.picks:
#             heapq.heappush(event_pq, (-p.get_event_happiness(i), p))

#     team1_pq = list(event_pq)
#     for p in team1.players:
#         heapq.heappush(team1_pq, (-p.get_event_happiness(i), p))

#     if team1_pq:
#         team1.add_and_decrease(heapq.heappop(team1_pq)[1], i)
#     if team1_pq:
#         team1.add_and_decrease(heapq.heappop(team1_pq)[1], i)

#     set_check_for_1 = set(team1_pq) 
#     team2_pq = list(event_pq)
#     team2_pq = list([item for item in team2_pq if item in set_check_for_1])
#     for p in team2.players:
#         heapq.heappush(team2_pq, (-p.get_event_happiness(i), p))
#     if team2_pq:
#         team2.add_and_decrease(heapq.heappop(team2_pq)[1], i)
#     if team2_pq:
#         team2.add_and_decrease(heapq.heappop(team2_pq)[1], i)

#     set_check_for_2 = set(team2_pq) 
#     team3_pq = list(event_pq)
#     team3_pq = list([item for item in team3_pq if item in set_check_for_1 and item in set_check_for_2])
#     for p in team3.players:
#         heapq.heappush(team3_pq, (-p.get_event_happiness(i), p))
#     if team3_pq:
#         team3.add_and_decrease(heapq.heappop(team3_pq)[1], i)
#     if team3_pq:
#         team3.add_and_decrease(heapq.heappop(team3_pq)[1], i)

for i in middle_option_flip:
    #add player to team 1, 2, 3 repeatedly while checking if adding another event for a player may increase happiness
    event_pq = []
    for p in (set(player_list)-team1.players - team2.players - team3.players):
        heapq.heappush(event_pq, (-p.get_event_happiness(i), p))
        
    
    team1_pq = list(event_pq)
    
    for p in team1.players:
        heapq.heappush(team1_pq, (-p.get_event_happiness(i), p))
    
    team1.add_and_decrease(heapq.heappop(team1_pq)[1], i)
    team1.add_and_decrease(heapq.heappop(team1_pq)[1], i)

    set_check_for_1 = set(team1_pq) 
    team2_pq = list(event_pq)
    team2_pq = list([item for item in team2_pq if item in set_check_for_1])
    for p in team2.players:
        heapq.heappush(team2_pq, (-p.get_event_happiness(i), p))
    team2.add_and_decrease(heapq.heappop(team2_pq)[1], i)
    team2.add_and_decrease(heapq.heappop(team2_pq)[1], i)

    set_check_for_2 = set(team2_pq) 
    team3_pq = list(event_pq)
    team3_pq = list([item for item in team3_pq if (item in set_check_for_1 and item in set_check_for_2)])
    for p in team3.players:
        #print(team3_pq[0][1].name)
        heapq.heappush(team3_pq, (-p.get_event_happiness(i), p))
    team3.add_and_decrease(heapq.heappop(team3_pq)[1], i)
    team3.add_and_decrease(heapq.heappop(team3_pq)[1], i)

# print(team1)
# print()
# print(team2)
# print()
# print(team3)
# print()

team1.finish_events()
team2.finish_events()
team3.finish_events()

print(team1)
print(len(team1.players))
print()
print(team2)
print(len(team2.players))
print()
print(team3)
print(len(team3.players))



for p in (list(set(player_list)-team1.players-team2.players-team3.players)):
    print(p.name)



